### ISSUE TITLE
can u write more  detail?

### ISSUE THREAD

**Issue by fyddaben** [synack/docker-rsync#11]
u say:
```Please note though that syncing happens only in one direction. If you want to sync back from a Docker container to your local machine, docker-rsync is not the tool you're looking for.```

but your example is 
```
Usage with docker-machine
```
I want to know how to connect , between container and local machine

so please write more `help` detail . very very thank you

**Comment by fyddaben** [comment]
ok. I read the `main.go` .and know a lot help info.

but ther is always some error
```
rsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-47/rsync/rsync.c(244) [sender=2.6.9]
rsync error: unexplained error (code 255) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-47/rsync/rsync.c(244) [sender=2.6.9]
```

**Comment by mattes** [comment]
I've experienced similar errors, too. It doesn't affect the syncing though. It would sill be interesting to find out, what's causing these errors.

**Comment by visitdigital** [comment]
I have run into this performance issue too. Can you help me implement this in a real life situation. This is my normal workflow:

In my Dockerfile directory i do this:

docker built -t mysite (this boots up the default VirtualBox Machine)

This volume defined here mounts my local Git Repo into the var/www folder on the Docker Machine
docker run -it --rm -p 8080:80 -p 8022:22 -v ~/websites/mysite/:/var/www/ -t mysite /bin/bash

How instead of mounting that directory do i simply rsync it using your git repo code? I have installed it but not entirely sure what to do next.

**Comment by mattes** [comment]
```
cd sync-this-directory
docker-rsync my-machine123
```
